---
title: "processLandCover"
output: pdf_document
---

```{r}
library(terra)#
library(tidyverse)
library(data.table)
library(sf) 
library(parallel)
library(R.utils)
library(lwgeom)
library(RCurl)
library(raster)
library(tigris)
library("fst")
library(ncdf4) # package for netcdf manipulation
library(velox)
```

```{r}
Dir="C:/Users/Pan Dulce/Downloads/supporting files/"
outDir = "C:/Users/Pan Dulce/Downloads/gpw-v4-population-count-rev11_2020_30_sec_asc/gpw-v4-population-count-rev11_2020_30_sec_asc/processed_data/"

gpw_grid_ca <- readRDS(paste0(outDir, "gpw_grid_ca.RDS"))

nc <- nc_open(paste0(Dir,"MCD12Q1.006_500m_aid0001.nc"))
####################################################################################

var_lc <- c("LC_Prop1","LC_Prop2",  "LC_Prop3","LC_Type1","LC_Type2", "LC_Type3", "LC_Type4", "LC_Type5")

gridlc_yr <- data.frame(matrix(NA,nrow = nrow(gpw_grid_ca), ncol = 0))
gridlc_yr$LATITUDE = gpw_grid_ca$LATITUDE
gridlc_yr$LONGITUDE = gpw_grid_ca$LONGITUDE

for (par in 1:length(var_lc)) {
  
  stack <- stack(paste0(Dir,"MCD12Q1.006_500m_aid0001.nc"),varname =paste0(var_lc[par])) %>% crop(extent(c(-124.5, -114, 32, 42.5)), keepres=TRUE)
  time <- stack@z[["time"]]
  
  gridlc_n_list <- matrix(nrow = nrow(gpw_grid_ca),ncol = length(time))
  for (i in 1:length(time)){
    layer_lc <- mean(stack[[i]], na.rm = T)
    layer_lc <- data.frame(rasterToPoints((layer_lc)))
    colnames(layer_lc)[1:2] <- c("LONGITUDE", "LATITUDE")
    layer_lc <- st_as_sf(layer_lc,
                          coords = c("LONGITUDE", "LATITUDE"),
                          crs = 4326,
                          remove = FALSE)
    layer_lc_gridded = st_drop_geometry(st_join(gpw_grid_ca, layer_lc, join=st_nearest_feature, suffix=c("", "_ignore"))[-c(3:4)]) 
   gridlc_n_list[,i] <- layer_lc_gridded[,3]
  }
  gridlc_n_df <- data.frame(gridlc_n_list)
  rm(gridlc_n_list)
  colnames(gridlc_n_df) <- paste0(var_lc[par], "_", 2001:2020)
  gridlc_yr <- cbind(gridlc_yr, gridlc_n_df)
}

saveRDS(gridlc_yr, file = paste0(outDir, "LandCover.RDS"))
```




